### ISSUE TITLE
Use Redis instead of database for caching hashes

### ISSUE THREAD

**Issue by Syfaro** [Syfaro/foxbot#12]
It's unlikely that there's a significant cache hit ratio on storing every unique Telegram file ID → hash (perhaps this should be measured first?). Now that Redis is getting pulled in with #11, it would make sense to store hashes there as there's no reason to require database overhead for recomputable values.

**Comment by Syfaro** [comment]
No longer blocked on merging #11

**Comment by cryptoquick** [comment]
Is this for storing img_hash hashes? Would there be memory concerns? I might experiment with an approach based on sled, since it's based on LSM-trees, which aren't limited by the amount of memory on the system. it may be over-optimization for vertical scaling, though. also, if you're using a redis cluster, that's better for load balancing, rather than being limited by sled block storage, and whatever network IOPS are available by your hosting provider.

**Comment by Syfaro** [comment]
Yep, it just needs to be a KV store for [`file_unique_id`](https://core.telegram.org/bots/api#photosize) to the i64 hash. I'm not terribly interested in persistence, as they're still relatively cheap to compute. Memory pressure shouldn't be too much of a concern as they're relatively small pairs, and they should expire after a week or something. 

It would basically just replace this block: https://github.com/Syfaro/foxbot/blob/master/src/models.rs#L296-L326

**Comment by cryptoquick** [comment]
neat! they're already async methods, so that's actually really trivial to implement

**Comment by Syfaro** [comment]
Over the last 24 hours the cache hit rate was just under 5% (61 hits, 1,286 misses). Not high, but more than I was expecting.
